# Source: cluster-api-aws/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: a7546c4b-667a-4aec-8fde-be8f2a389839-capi-aws
  namespace: a7546c4b-667a-4aec-8fde-be8f2a389839
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: a7546c4b-667a-4aec-8fde-be8f2a389839-capi-aws
subjects:
- kind: ServiceAccount
  name: a7546c4b-667a-4aec-8fde-be8f2a389839-capi-aws
